export const GET_LIBRARY_LIST_REQUEST = '@@libraries/GET_LIBRARY_LIST_REQUEST';
export const GET_LIBRARY_LIST_SUCCESS = '@@libraries/GET_LIBRARY_LIST_SUCCESS';
export const GET_LIBRARY_LIST_FAILURE = '@@libraries/GET_LIBRARY_LIST_FAILURE';